### ISSUE TITLE
Kernel panic caused by having more than 1 drive/img after starting to load AHCI module. (wait nvm ignore)

### ISSUE THREAD

**Issue by lapinclown** [kot-org/new-kot#5]
#  what the hell just happened

When beginning to load the AHCI module, if there's more than one drive (already tested 2 and 3 drives with QEMU) connected, it would panic with this message :

` [kernel] pnc: Assertion failed: load_parititons(device_partitions) == 0, file ../../source/interface.c, function add_storage_device, line 16`

#  how to reproduce this ?

literally add one or more img to the qemu command line option thing i don't know.

**Comment by lapinclown** [comment]
i made an oopsie. sry

**Comment by raphm4044** [comment]
The ahci module doesn't support multiple disks

**Comment by lapinclown** [comment]
that explains why
